In [2]:
import numpy as np

In [8]:
coeff_A = [3, 3, 0]
coeff_B = [2, 2, 2]
coeff_C = [6, 4, 4]
coeff_D = [6, 4, 4]
coeff_EF = [54, 36, 36]
coeff_G = [9, 6, 6]


coeff_mat_ACG = np.array([coeff_A, coeff_C, coeff_G])

print("ACG: ")
print(coeff_mat_ACG)

coeff_mat_ABC = np.array([coeff_A, coeff_B, coeff_C])

print("ABC: ")
print(coeff_mat_ABC)

print("shape of ABC:")
print(coeff_mat_ABC.shape)


ACG: 
[[3 3 0]
 [6 4 4]
 [9 6 6]]
ABC: 
[[3 3 0]
 [2 2 2]
 [6 4 4]]
shape of ABC:
(3, 3)


In [11]:
def mat_size(ndarray):
    mat_size = ndarray.shape
    row_number = mat_size[0]
    col_number = mat_size[1]
    return row_number, col_number

In [13]:
row, col = mat_size(coeff_mat_ABC)
print(row)
print(col)

3
3


In [17]:
np.random.normal(0, 1, (coeff_mat_ABC.shape))

array([[-0.32838749, -0.9613948 ,  0.79534849],
       [ 0.18984885, -0.74620523, -0.08779253],
       [-0.45543865,  2.44022157, -0.27334675]])

In [16]:
coeff_mat_ABC_inv = np.linalg.inv(coeff_mat_ABC)
print(coeff_mat_ABC_inv)

[[ 7.40148683e-17 -1.00000000e+00  5.00000000e-01]
 [ 3.33333333e-01  1.00000000e+00 -5.00000000e-01]
 [-3.33333333e-01  5.00000000e-01  2.77555756e-17]]


In [64]:
ptb_on_ABC_inv = np.random.normal(0, 0.1, coeff_mat_ABC.T.shape)
err_on_ABC_inv = np.dot(coeff_mat_ABC_inv, ptb_on_ABC_inv)

print(err_on_ABC_inv)

[[ 0.11574379 -0.1411183  -0.12497416]
 [-0.0573074   0.16621342  0.11045566]
 [-0.04813959  0.02897176  0.0474265 ]]


In [65]:
ptbed_ABC_inv = coeff_mat_ABC_inv + err_on_ABC_inv

In [66]:
test_data_2327_DMF = {
    'solv' : 'DMF',
    'sample_id' : '2327',
    'rxn_days' : 3,
    'A' : 3,
    'B' : 1.9,
    'C' : 6.34,
    'D' : 10.57,
    'EF' : 76.7,
    'G' : 12.6
}


test_data_2328_DMSO = {
    'solv' : 'DMSO',
    'sample_id' : '2328',
    'rxn_days' : 3,
    'A' : 3,
    'B' : 1.79,
    'C' : 6.12,
    'D' : 12.06,
    'EF' : 77.92,
    'G' : 12.07
}


In [67]:
def mat_B(test_data, peak_list = ['A', 'B', 'C']):
    
    mat_B_list = []
    
    for i, peak in enumerate(peak_list):
        peak_name = peak
        peak_int = test_data[peak]
        print(peak_name)
        print(peak_int)
        mat_B_list.append(peak_int)
    
    mat_B = np.array(mat_B_list)
    
    return mat_B

mat_B_test = mat_B(test_data_2327_DMF)
print(mat_B_test.shape)

A
3
B
1.9
C
6.34
(3,)


In [71]:
before_norm_result = np.dot(ptbed_ABC_inv, mat_B_test)

In [72]:
def norm_coeff(ndarray):
    
    sum_array = np.sum(ndarray)
    norm_list = []
    
    for i, item in enumerate(ndarray):
        norm_item = item/sum_array
        norm_list.append(norm_item)
    
    norm_array = np.array(norm_list)
    
    return norm_array

In [73]:
norm_result = norm_coeff(before_norm_result)
print(norm_result)

[0.43085209 0.44431829 0.12482962]


In [75]:
mat_B_DMSO = mat_B(test_data_2328_DMSO)
DMSO_before_norm = np.dot(ptbed_ABC_inv, mat_B_DMSO)
DMSO_norm = norm_coeff(DMSO_before_norm)
print(DMSO_norm)

A
3
B
1.79
C
6.12
[0.48999582 0.43428049 0.07572369]


In [ ]:
coeff_A = [3, 3, 0]
coeff_B = [2, 2, 2]
coeff_C = [6, 4, 4]
coeff_D = [6, 4, 4]
coeff_EF = [54, 36, 36]
coeff_G = [9, 6, 6]


coeff_mat_ABC = np.array([coeff_A, coeff_B, coeff_C])
coeff_mat_ABC_inv = np.linalg.inv(coeff_mat_ABC)
ptb_on_ABC_inv = np.random.normal(0, 0.1, coeff_mat_ABC.T.shape)
err_on_ABC_inv = np.dot(coeff_mat_ABC_inv, ptb_on_ABC_inv)
ptbed_ABC_inv = coeff_mat_ABC_inv + err_on_ABC_inv



def calc_sp_ratio(test_data, peak_list = ['A', 'B', 'C']):
    
    mat_B = mat_B(test_data, peak_list = peak_list)
    

In [23]:
coeff_mat = np.array([[3, 3, 0], [2, 2, 2], [6, 4, 4], [54, 36, 36], [9, 6, 6]])
nmr_int_mat = np.array([3, 1.9, 10.57, 76.7, 12.6])
lpinv_coeff_mat = np.linalg.pinv(coeff_mat)
stc_vec = np.dot(lpinv_coeff_mat, nmr_int_mat)
print(stc_vec)

[ 2.37163205 -1.37163205 -0.05      ]


In [31]:
rslt_vld_test = np.dot(coeff_mat, stc_vec)
print('result validation: ')
print(rslt_vld_test)

vld_test_err = rslt_vld_test - nmr_int_mat
print('error: ')
print(vld_test_err)

result validation: 
[ 3.          1.9         8.54326409 76.88937685 12.81489614]
error: 
[-2.48689958e-14 -1.19904087e-14 -2.02673591e+00  1.89376855e-01
  2.14896142e-01]


issue: 6 equations, 3 unknowns -> reliability of results?
eq 2 and 3 are expected to be same, but from the NMR integral, not really.
same coefficient -> redundant information?

XF2327

In [2]:
# DMF, 3d, xf2327

coeff_mat = np.array([[3, 3, 0], [2, 2, 2], [6, 4, 4], [6, 4, 4], [54, 36, 36], [9, 6, 6]])
nmr_int_mat = np.array([3, 1.9, 6.34, 10.57, 76.7, 12.6])

# stc_vec = np.linalg.solve(coeff_mat, nmr_int_mat)

# stc_vec

In [3]:
lpinv_coeff_mat = np.linalg.pinv(coeff_mat)
stc_vec = np.dot(lpinv_coeff_mat, nmr_int_mat)

In [4]:
stc_vec
print(stc_vec)
print(sum(stc_vec))
print(stc_vec/sum(stc_vec))

[ 2.35870968 -1.35870968 -0.05      ]
0.950000000000001
[ 2.48285229 -1.43022071 -0.05263158]


In [5]:
coeff_mat = np.array([[3, 3, 0], [2, 2, 2], [6, 4, 4], [6, 4, 4], [54, 36, 36], [9, 6, 6]]) # calculated from three products S3E0, S2E0 and S2E1

def prod_ratio(ref_H, ortho_H, alpha_H, beta_H, alkyl_Hs, methyl_H, sample_id):

    nmr_int_mat = np.array([ref_H, ortho_H, alpha_H, beta_H, alkyl_Hs, methyl_H])

    lpinv_coeff_mat = np.linalg.pinv(coeff_mat)
    stc_vec = np.dot(lpinv_coeff_mat, nmr_int_mat)

    x, y, z = stc_vec
    total_stc = sum(stc_vec)
    px = x/total_stc
    py = y/total_stc
    pz = z/total_stc

    print(sample_id, ':\n', 'S3E0: ', px, '\n', 'S2E0: ', py, '\n', 'S2E1: ', pz)

In [6]:
prod_ratio(3, 1.9, 6.34, 10.57, 76.7, 12.6, 'XF2327_DMF_3d')

XF2327_DMF_3d :
 S3E0:  2.4828522920203677 
 S2E0:  -1.4302207130730051 
 S2E1:  -0.05263157894736266


In [7]:
prod_ratio(3, 1.79, 6.12, 12.06, 77.92, 12.07, 'XF2328_DMSO_3d')

XF2328_DMSO_3d :
 S3E0:  2.833401595701102 
 S2E0:  -1.7160831599469197 
 S2E1:  -0.11731843575418227


In [8]:
# if unreacted BrAlkane was found, an additional correction step will be carried out to remove overlap fraction on the alkyl chain signals.

def prod_ratio_rm_brak(ref_H, ortho_H, ori_alpha_H, ori_beta_H, ori_alkyl_Hs, ori_methyl_H, br_ak_alpha_Hs, sample_id):

    alpha_H_rm = br_ak_alpha_Hs
    beta_H_rm = br_ak_alpha_Hs
    alkyl_Hs_rm = 9*br_ak_alpha_Hs
    methyl_H_rm = 1.5*br_ak_alpha_Hs

    updt_alpha_H = ori_alpha_H - alpha_H_rm
    updt_beta_H = ori_beta_H - beta_H_rm
    updt_alkyl_Hs = ori_alkyl_Hs - alkyl_Hs_rm
    updt_methyl_H = ori_methyl_H - methyl_H_rm

    prod_ratio(ref_H, ortho_H, updt_alpha_H, updt_beta_H, updt_alkyl_Hs, updt_methyl_H, sample_id)


In [9]:
prod_ratio_rm_brak(3, 3.62, 6.62, 6.77, 74.97, 11.92, 1.34, 'XF2307_DMF_2d')

XF2307_DMF_2d :
 S3E0:  -0.08245167771098937 
 S2E0:  0.634937865556297 
 S2E1:  0.44751381215469227


In [10]:
prod_ratio_rm_brak(3, 7.66, 6.81, 6.84, 66.78, 10.18, 2.37, 'XF2307_DMF_2d_2_rxl_rm_layer')

XF2307_DMF_2d_2_rxl_rm_layer :
 S3E0:  -1.3447355726897519 
 S2E0:  1.6058321784338856 
 S2E1:  0.7389033942558663


the above cell suggests the recrystallisation can selectively remove disubstituted products and hydrolysis derivatives

but it also could be the inaccuracy led by signals overlapped with solvent residue (ortho H and alkyl Hs)

In [11]:
prod_ratio_rm_brak(3, 3.27, 6.24, 10.87, 84.28, 15.19, 1.56, 'XF2308_tBuOH_24_DMSO_76_2d')
prod_ratio_rm_brak(3, 4.03, 7.07, 6.95, 57.29, 17.45, 0, 'XF2308_tBuOH_24_DMSO_76_2d_2_rxl_rm_layer')

XF2308_tBuOH_24_DMSO_76_2d :
 S3E0:  0.38702502981875464 
 S2E0:  0.22459576528828068 
 S2E1:  0.3883792048929647
XF2308_tBuOH_24_DMSO_76_2d_2_rxl_rm_layer :
 S3E0:  -0.38220676306004064 
 S2E0:  0.8784846786927999 
 S2E1:  0.5037220843672408


In [12]:
prod_ratio_rm_brak(3, 3.92, 6.64, 7.98, 69.2, 15.88, 1.64, 'XF2309_IPA_23_DMSO_77_2d')
prod_ratio_rm_brak(3, 3.56, 6.58, 6.5, 71.99, 14.79, 0.39, 'XF2309_IPA_23_DMSO_77_2d_2_rxl_rm_layer')

XF2309_IPA_23_DMSO_77_2d :
 S3E0:  -0.4396732299958097 
 S2E0:  0.9498773116284681 
 S2E1:  0.4897959183673416
XF2309_IPA_23_DMSO_77_2d_2_rxl_rm_layer :
 S3E0:  0.14151207618043413 
 S2E0:  0.4202856766285576 
 S2E1:  0.43820224719100836


In [13]:
prod_ratio_rm_brak(3, 2.19, 7.91, 7.66, 77.07, 11.41, 0.03, 'XF2310_IPA_30_ACN_31_NMI_39_2d')

XF2310_IPA_30_ACN_31_NMI_39_2d :
 S3E0:  1.8766319848953492 
 S2E0:  -0.9633899757629323 
 S2E1:  0.0867579908675831


In [14]:
prod_ratio_rm_brak(3, 2.49, 6.55, 7.95, 86.86, 14.19, 1.03, 'XF2311_EA_10_DMSO_73_EtOH_17_2d')
prod_ratio_rm_brak(3, 7.97, 6.26, 4.87, 69.58, 15.71, 0.37, 'XF2311_EA_10_DMSO_73_EtOH_17_2d_2_rxl_rm_layer')

XF2311_EA_10_DMSO_73_EtOH_17_2d :
 S3E0:  1.4376450081852354 
 S2E0:  -0.634432156779614 
 S2E1:  0.19678714859437843
XF2311_EA_10_DMSO_73_EtOH_17_2d_2_rxl_rm_layer :
 S3E0:  -1.073692770175546 
 S2E0:  1.3246337990337718 
 S2E1:  0.7490589711417743


In [15]:
prod_ratio_rm_brak(3, 13.88, 5.5, 11.38, 60.23, 10.34, 0, 'XF2312_DMSO_79_EtOH_21_2d') # this group may have issue with the ortho_H integral due to large overlap with CDCl3 peak

XF2312_DMSO_79_EtOH_21_2d :
 S3E0:  -1.5145148613587747 
 S2E0:  1.6586070803789563 
 S2E1:  0.8559077809798183


In [16]:
prod_ratio_rm_brak(3, 7.93, 7.36, 7.26, 49.44, 13.84, 0, 'XF2313_EA_23_DMSO_77_2d')

XF2313_EA_23_DMSO_77_2d :
 S3E0:  -1.2894720298210502 
 S2E0:  1.5416788394049168 
 S2E1:  0.7477931904161332


In [17]:
prod_ratio_rm_brak(3, 2.4, 5.87, 9.49, 65.49, 13.4, 0, 'XF2319_tBuOH_19_DMSO_76_EtOH_5_2d')
prod_ratio_rm_brak(3, 2.4, 6.26, 6.93, 49.36, 13.26, 0, 'XF2319_tBuOH_19_DMSO_76_EtOH_5_2d_F_crash_from_filtrate')
prod_ratio_rm_brak(3, 2.2, 5.9, 6.91, 52.86, 8.58, 0, 'XF2319_tBuOH_19_DMSO_76_EtOH_5_2d_F_crash_from_filtrate_rxl_rm_layer')

XF2319_tBuOH_19_DMSO_76_EtOH_5_2d :
 S3E0:  1.054105571847504 
 S2E0:  -0.22077223851417152 
 S2E1:  0.16666666666666752
XF2319_tBuOH_19_DMSO_76_EtOH_5_2d_F_crash_from_filtrate :
 S3E0:  0.33294232649071076 
 S2E0:  0.5003910068426246 
 S2E1:  0.16666666666666466
XF2319_tBuOH_19_DMSO_76_EtOH_5_2d_F_crash_from_filtrate_rxl_rm_layer :
 S3E0:  0.673527059450809 
 S2E0:  0.23556384964010055 
 S2E1:  0.09090909090909047


In [18]:
prod_ratio_rm_brak(3, 2.15, 6.44, 7.4, 62.37, 10.4, 0, 'XF2320_TEA_6_DMSO_94_2d')
prod_ratio_rm_brak(3, 2.47, 6.38, 6.67, 64.77, 10.81, 0, 'XF2320_TEA_6_DMSO_94_2d_crude')

XF2320_TEA_6_DMSO_94_2d :
 S3E0:  1.2231876150855863 
 S2E0:  -0.29295505694605256 
 S2E1:  0.06976744186046627
XF2320_TEA_6_DMSO_94_2d_crude :
 S3E0:  0.9073574981894144 
 S2E0:  -0.0976408989991307 
 S2E1:  0.19028340080971626


In [19]:
prod_ratio_rm_brak(3, 2.04, 5.92, 6.46, 48.31, 7.18, 0, 'XF2321_DMSO_75_TEA_5_EtOH_20_2d')
prod_ratio_rm_brak(3, 2.31, 6.06, 7.11, 60.11, 10.76, 0, 'XF2321_DMSO_75_TEA_5_EtOH_20_2d_crude')

XF2321_DMSO_75_TEA_5_EtOH_20_2d :
 S3E0:  0.6332010810189138 
 S2E0:  0.34719107584383174 
 S2E1:  0.01960784313725448
XF2321_DMSO_75_TEA_5_EtOH_20_2d_crude :
 S3E0:  0.8959896408576737 
 S2E0:  -0.030188775056807775 
 S2E1:  0.1341991341991341


The ortho_H term and alkyl Hs might lead to mis prediction because it is deconvoluted from the overlapped peak with solvent residue (CDCl3, D2O).

The following attempt will remove those dimensions.

In [20]:
coeff_mat = np.array([[3, 3, 0], [6, 4, 4], [6, 4, 4], [9, 6, 6]]) # calculated from three products S3E0, S2E0 and S2E1

def prod_ratio_no_ovlp(ref_H, alpha_H, beta_H, methyl_H, sample_id):

    nmr_int_mat = np.array([ref_H, alpha_H, beta_H, methyl_H])

    lpinv_coeff_mat = np.linalg.pinv(coeff_mat)
    stc_vec = np.dot(lpinv_coeff_mat, nmr_int_mat)

    x, y, z = stc_vec
    total_stc = sum(stc_vec)
    px = x/total_stc
    py = y/total_stc
    pz = z/total_stc

    print(sample_id, ':\n', 'S3E0: ', px, '\n', 'S2E0: ', py, '\n', 'S2E1: ', pz)

def prod_ratio_rm_brak_no_ovlp(ref_H, ori_alpha_H, ori_beta_H, ori_methyl_H, br_ak_alpha_Hs, sample_id):

    alpha_H_rm = br_ak_alpha_Hs
    beta_H_rm = br_ak_alpha_Hs
    methyl_H_rm = 1.5*br_ak_alpha_Hs

    updt_alpha_H = ori_alpha_H - alpha_H_rm
    updt_beta_H = ori_beta_H - beta_H_rm
    updt_methyl_H = ori_methyl_H - methyl_H_rm

    prod_ratio_no_ovlp(ref_H, updt_alpha_H, updt_beta_H, updt_methyl_H, sample_id)


In [21]:
prod_ratio_rm_brak_no_ovlp(3, 7.36, 7.26, 13.84, 0, 'XF2313_EA_23_DMSO_77_2d_no_ortho_alkyl_test')

XF2313_EA_23_DMSO_77_2d_no_ortho_alkyl_test :
 S3E0:  0.39377537212449254 
 S2E0:  0.18132611637347731 
 S2E1:  0.4248985115020302


In [22]:
prod_ratio_rm_brak_no_ovlp(3, 6.81, 6.84, 10.18, 2.37, 'XF2307_DMF_2d_2_rxl_rm_layer_no_ovlp')
prod_ratio_rm_brak_no_ovlp(3, 7.07, 6.95, 17.45, 0, 'XF2308_tBuOH_24_DMSO_76_2d_2_rxl_rm_layer_no_ovlp')
prod_ratio_rm_brak_no_ovlp(3, 5.5, 11.38, 10.34, 0, 'XF2312_DMSO_79_EtOH_21_2d_no_ovlp')
prod_ratio_rm_brak_no_ovlp(3, 6.26, 6.93, 13.26, 0, 'XF2319_tBuOH_19_DMSO_76_EtOH_5_2d_F_crash_from_filtrate_no_ovlp')
prod_ratio_rm_brak_no_ovlp(3, 5.92, 6.46, 7.18, 0, 'XF2321_DMSO_75_TEA_5_EtOH_20_2d_no_ovlp')

XF2307_DMF_2d_2_rxl_rm_layer_no_ovlp :
 S3E0:  0.5359171774555237 
 S2E0:  0.6077515323665723 
 S2E1:  -0.14366870982209598
XF2308_tBuOH_24_DMSO_76_2d_2_rxl_rm_layer_no_ovlp :
 S3E0:  0.37559101654846333 
 S2E0:  0.1267730496453896 
 S2E1:  0.49763593380614707
XF2312_DMSO_79_EtOH_21_2d_no_ovlp :
 S3E0:  0.4079795142904345 
 S2E0:  0.22393854287130316 
 S2E1:  0.36808194283826234
XF2319_tBuOH_19_DMSO_76_EtOH_5_2d_F_crash_from_filtrate_no_ovlp :
 S3E0:  0.40445808431594255 
 S2E0:  0.21337425294782722 
 S2E1:  0.3821676627362303
XF2321_DMSO_75_TEA_5_EtOH_20_2d_no_ovlp :
 S3E0:  0.4774078478002377 
 S2E0:  0.43222354340071345 
 S2E1:  0.09036860879904886


try to remove beta H signals for the final 2321:

In [23]:
coeff_mat = np.array([[3, 3, 0], [6, 4, 4], [9, 6, 6]]) # calculated from three products S3E0, S2E0 and S2E1

def prod_ratio_no_ovlp_b(ref_H, alpha_H, methyl_H, sample_id):

    nmr_int_mat = np.array([ref_H, alpha_H, methyl_H])

    lpinv_coeff_mat = np.linalg.pinv(coeff_mat)
    stc_vec = np.dot(lpinv_coeff_mat, nmr_int_mat)

    x, y, z = stc_vec
    total_stc = sum(stc_vec)
    px = x/total_stc
    py = y/total_stc
    pz = z/total_stc

    print(sample_id, ':\n', 'S3E0: ', px, '\n', 'S2E0: ', py, '\n', 'S2E1: ', pz)

def prod_ratio_rm_brak_no_ovlp_b(ref_H, ori_alpha_H, ori_methyl_H, br_ak_alpha_Hs, sample_id):

    alpha_H_rm = br_ak_alpha_Hs
    methyl_H_rm = 1.5*br_ak_alpha_Hs

    updt_alpha_H = ori_alpha_H - alpha_H_rm
    updt_methyl_H = ori_methyl_H - methyl_H_rm

    prod_ratio_no_ovlp_b(ref_H, updt_alpha_H, updt_methyl_H, sample_id)

In [24]:
prod_ratio_rm_brak_no_ovlp_b(3, 5.92, 7.18, 0, 'XF2321_DMSO_75_TEA_5_EtOH_20_2d_no_ovlp_b')

XF2321_DMSO_75_TEA_5_EtOH_20_2d_no_ovlp_b :
 S3E0:  0.49269830733488235 
 S2E0:  0.47809492200464654 
 S2E1:  0.029206770660471136


remove methyl H

In [25]:
coeff_mat = np.array([[3, 3, 0], [6, 4, 4], [6, 4, 4]]) # calculated from three products S3E0, S2E0 and S2E1

def prod_ratio_no_ovlp_m(ref_H, alpha_H, beta_H, sample_id):

    nmr_int_mat = np.array([ref_H, alpha_H, beta_H])

    lpinv_coeff_mat = np.linalg.pinv(coeff_mat)
    stc_vec = np.dot(lpinv_coeff_mat, nmr_int_mat)

    x, y, z = stc_vec
    total_stc = sum(stc_vec)
    px = x/total_stc
    py = y/total_stc
    pz = z/total_stc

    print(sample_id, ':\n', 'S3E0: ', px, '\n', 'S2E0: ', py, '\n', 'S2E1: ', pz)

def prod_ratio_rm_brak_no_ovlp_m(ref_H, ori_alpha_H, ori_beta_H, br_ak_alpha_Hs, sample_id):

    alpha_H_rm = br_ak_alpha_Hs
    beta_H_rm = br_ak_alpha_Hs

    updt_alpha_H = ori_alpha_H - alpha_H_rm
    updt_beta_H = ori_beta_H - beta_H_rm

    prod_ratio_no_ovlp_m(ref_H, updt_alpha_H, updt_beta_H, sample_id)

In [26]:
prod_ratio_rm_brak_no_ovlp_m(3, 5.92, 6.46, 0, 'XF2321_DMSO_75_TEA_5_EtOH_20_2d_no_ovlp_m')

XF2321_DMSO_75_TEA_5_EtOH_20_2d_no_ovlp_m :
 S3E0:  0.44771528998242516 
 S2E0:  0.34314586994727597 
 S2E1:  0.20913884007029887
